package com.android.logger.utils

import com.android.logger.BuildConfig
import java.util.concurrent.TimeUnit


const val MIN_FILE_DISPOSAL_BY_ARCHIVE_DAYS_COUNT = 3
const val MIN_FILE_DISPOSAL_BY_DELETION_DAYS_COUNT = 14

const val WORKER_TASK_TYPE_KEY = "WORKER_TASK_TYPE_KEY"
const val TYPE_UNMATCHED = 0
const val TYPE_DELETE = 1
const val TYPE_ARCHIVE = 2

const val WORKER_DISPOSE_TIME_IN_DAYS_KEY = "WORKER_DISPOSE_TIME_IN_DAYS_KEY"
const val WORKER_DISPOSE_LOCATION_KEY = "WORKER_DISPOSE_LOCATION_KEY"
const val WORKER_BASE_LOCATION_KEY = "WORKER_BASE_LOCATION_KEY"
const val WORKER_JOB_TAG = "WORKER_JOB_TAG"

val WORKER_REPETITION_TIME_UNIT = TimeUnit.DAYS
const val WORKER_REPETITION_FREQUENCY = 1L

const val DEFAULT_FILE_NAME = "Log"
const val DEFAULT_MAX_FILE_SIZE_IN_KB = 1024 * 5
const val DEFAULT_SYSTEM_LOG_ENABLED = true
const val DEFAULT_FILE_LOG_ENABLED = true

const val DEFAULT_PACKAGE_NAME = BuildConfig.LIBRARY_PACKAGE_NAME

